import Navbar from "@/components/Navbar/Navbar";
import ToggleSwitch from "@/components/ToggleSwitch";
import { type NextPage } from "next";
import { Session } from "next-auth";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ToastContainer, toast } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';



const Home: NextPage = () => {
  const { data, status } = useSession();

  useEffect(() => {
    toast.success("Welcome to my portfolio", {
      position: "top-right",
      autoClose: 2000,
      hideProgressBar: true,
    });
  }, [])


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <div className="min-h-screen bg-gradient-to-b from-[#1e1629] to-[#242038] w-full">
          <div className="w-full shadow-xl">
            <Navbar />
          </div>
          <div>
            <h1 className="text-4xl text-white">Hello World</h1>
          </div>

        </div>
        <ToastContainer />
      </main>
    </>
  );
};

export default Home;
