import Navbar from "@/components/Navbar/Navbar";
import { type NextPage } from "next";
// import { Session } from "next-auth";
// import { useSession } from "next-auth/react";
import Head from "next/head";
// import Link from "next/link";
import { useEffect } from "react";
import { ToastContainer, toast } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';



const Home: NextPage = () => {

  // Function to display the text character by character
  function typeWriter(text: string, element: any) {
    let charIndex = 0;
    const typingInterval = setInterval(() => {
      if (charIndex < text.length) {
        element.textContent += text.charAt(charIndex);
        charIndex++;
      } else {
        clearInterval(typingInterval);
      }
    }, 100); // Adjust the typing speed by changing the interval (in milliseconds)
  }

  // Define the text to be typed
  const text = "Welcome to my website";

  useEffect(() => {
    typeWriter(text, document.getElementById("typed-text"));
    toast.success("Welcome to my portfolio", {
      position: "top-right",
      autoClose: 2000,
      hideProgressBar: true,
    });
  }, [])


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <div className="min-h-screen bg-gradient-to-b from-[#1e1629] to-[#242038] w-full">
          <div className="w-full shadow-xl">
            <Navbar />
          </div>
          <div>
            <div>
              <div className="typewriter">
                <h1 className="text-white text-4xl font-bold text-center mt-10">
                  <span id="typed-text"></span>
                </h1>
              </div>
            </div>
          </div>

        </div>
        <ToastContainer />
      </main>
    </>
  );
};

export default Home;
